# Generated by Django 6.0.1 on 2026-01-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_maintenance_scheduled_date_alter_maintenance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='scheduled_date',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='core.room'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
