# Generated by Django 6.0.1 on 2026-01-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_maintenance_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duepayment',
            name='is_recurring_monthly',
            field=models.BooleanField(default=True, help_text='If True, this payment recurs monthly'),
        ),
    ]
