# Generated by Django 6.0.1 on 2026-01-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_duepayment_is_recurring_monthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('short_term', 'Short-term (per night)'), ('monthly', 'Monthly Rental')], default='short_term', help_text='Type of booking', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='monthly_due_date',
            field=models.IntegerField(blank=True, help_text='Day of month when rent is due (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rent amount (for monthly rentals)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(blank=True, help_text='Leave blank for ongoing tenancy', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('active', 'Active Tenant'), ('ended', 'Tenancy Ended')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total for the booking period', max_digits=10),
        ),
    ]
