# Generated by Django 6.0.1 on 2026-01-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booking_booking_type_booking_monthly_due_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Apartment Rental', 'verbose_name_plural': 'Apartment Rentals'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Apartment Unit', 'verbose_name_plural': 'Apartment Units'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_type',
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(verbose_name='Move-in Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(blank=True, null=True, verbose_name='Move-out Date (Leave blank for ongoing)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=1, verbose_name='Number of Occupants'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='monthly_due_date',
            field=models.IntegerField(default=1, verbose_name='Rent Due Date (1-31)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Rent (₱)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('active', 'Active Tenant'), ('ended', 'Tenancy Ended'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Rental Amount'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(verbose_name='Maximum Occupants'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monthly Rent (₱)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Unit Number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('studio', 'Studio Unit'), ('deluxe', '1 Bedroom'), ('suite', '2+ Bedroom')], max_length=20, verbose_name='Unit Type'),
        ),
    ]
