# Generated by Django 6.0.1 on 2026-01-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fix_notification_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='duepayment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='duepayment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='room',
        ),
        migrations.RemoveField(
            model_name='event',
            name='room',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='is_cleared',
            field=models.BooleanField(default=False, help_text='When cleared, hidden from view but remains in database'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lease', 'Lease'), ('payment', 'Payment'), ('system', 'System')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='DuePayment',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
