# Generated by Django 6.0.1 on 2026-02-24 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_maintenance_options_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField()),
                ('photo_order', models.IntegerField(default=0, help_text='Order of photo (0-3)')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.apartment')),
            ],
            options={
                'ordering': ['photo_order'],
                'unique_together': {('apartment', 'photo_order')},
            },
        ),
    ]
