# Generated by Django 6.0.2 on 2026-02-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_apartmentphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentphoto',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='apartmentphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_photos/'),
        ),
    ]
