from django.urls import path
from core import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('apartments/', views.apartments, name='apartments'),
    path('apartment/<int:apartment_id>/', views.apartment_detail, name='apartment_detail'),
    path('password-reset/', views.password_reset_request, name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    
    path('dashboard/', views.dashboard, name='dashboard'),
    path('apartment/<int:apartment_id>/lease/', views.lease_apartment, name='lease_apartment'),
    path('lease/<int:lease_id>/confirmation/', views.lease_confirmation, name='lease_confirmation'),
    path('lease/<int:lease_id>/detail/', views.lease_detail, name='lease_detail'),
    path('lease/<int:lease_id>/add-payment/', views.add_payment, name='add_payment'),
    path('lease/<int:lease_id>/cancel/', views.cancel_lease, name='cancel_lease'),
    path('my-leases/', views.my_leases, name='my_leases'),
    path('payments/', views.payments, name='payments'),
    path('maintenance/', views.maintenance, name='maintenance'),
    path('notifications/', views.notifications, name='notifications'),
    path('calendar/', views.tenant_calendar, name='tenant_calendar'),
    path('calendar/request-event/', views.request_event, name='request_event'),
    path('change-password/', views.change_password, name='change_password'),
    path('settings/', views.settings, name='settings'),
    path('logout/', views.user_logout, name='logout'),
    
    path('staff-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('staff/leases/', views.manage_leases, name='manage_leases'),
    path('staff/lease/<int:lease_id>/update-status/', views.update_lease_status, name='update_lease_status'),
    path('staff/apartments/', views.manage_apartments, name='manage_apartments'),
    path('staff/apartments/add/', views.add_apartment, name='add_apartment'),
    path('staff/apartment/<int:apartment_id>/toggle/', views.toggle_apartment_availability, name='toggle_apartment_availability'),
    path('staff/tenants/', views.manage_tenants, name='manage_tenants'),
    path('staff/maintenance/', views.staff_maintenance_list, name='staff_maintenance'),
    path('staff/maintenance/<int:maintenance_id>/action/', views.staff_maintenance_action, name='staff_maintenance_action'),
    path('staff/calendar/', views.admin_calendar, name='admin_calendar'),
    path('staff/calendar/add-event/', views.add_admin_event, name='add_admin_event'),
    path('staff/calendar/approve/<int:event_id>/', views.approve_event, name='approve_event'),
    path('staff/calendar/delete/<int:event_id>/', views.delete_event, name='delete_event'),
    path('staff/calendar/time-off/', views.set_time_off, name='set_time_off'),
    path('staff/dashboard/export-sales-csv/', views.export_sales_csv, name='export_sales_csv'),
    path('staff/dashboard/export-sales-pdf/', views.export_sales_pdf, name='export_sales_pdf'),
    
    path('check-availability/', views.check_availability, name='check_availability'),
    path('api/calendar/events/', views.api_calendar_events, name='api_calendar_events'),
    path('api/calendar/events/create/', views.api_create_event, name='api_create_event'),
    path('api/calendar/events/<int:event_id>/action/', views.api_event_action, name='api_event_action'),
    path('api/calendar/events/<int:event_id>/edit/', views.api_edit_event, name='api_edit_event'),
    path('api/calendar/events/<int:event_id>/delete/', views.api_delete_event, name='api_delete_event'),
    path('api/notification-count/', views.api_notification_count, name='api_notification_count'),
    path('api/notification/<int:notification_id>/mark-read/', views.api_mark_notification_read, name='api_mark_notification_read'),
    path('api/maintenance/<int:maintenance_id>/clear/', views.clear_maintenance_request, name='clear_maintenance_request'),
    path('api/payment-notifications/', views.api_payment_notifications, name='api_payment_notifications'),
    path('api/lease/<int:lease_id>/payment-summary/', views.api_lease_payment_summary, name='api_lease_payment_summary'),
    path('api/due-dates-count/', views.api_due_dates_count, name='api_due_dates_count'),
    path('api/open-in-chrome/', views.open_in_chrome, name='open_in_chrome'),
    path('api/upload-apartment-photos/', views.upload_apartment_photos, name='upload_apartment_photos'),
    path('api/delete-apartment-photo/<int:photo_id>/', views.delete_apartment_photo, name='delete_apartment_photo'),
]
